apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tnr-fe
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tnr-fe
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: ./k8s
    repoURL: https://github.com/HasseneFliss/multi-tier-kubernetes
    targetRevision: {{ .Values.spec.source.targetRevision }}
